sudo: false
dist: trusty
language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - composer test

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $HOME/.composer/cache
